# Generated by Django 2.0.2 on 2018-02-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
