# Generated by Django 2.0.2 on 2018-02-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userfeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeed',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='UserFeed',
        ),
    ]
